packages:
  # old
  # - 'apps/*'
  # - 'apps/agent-tars/src/*'
  # - 'apps/ui-tars/src/*'
  # - 'packages/ui-tars/**'
  # - 'packages/agent-infra/**'
  # - 'packages/common/*'
  # - '!packages/ui-tars/visualizer'
  # new
  - 'apps/nest-api'
  - 'apps/react-web'
